// react-app/src/pages/Login.jsx
import React, { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { authService } from '../services/authService';
import { useToast } from '../context/ToastContext';
import '../styles/auth.css';

export const Login = () => {
  const [formData, setFormData] = useState({ email: '', password: '' });
  const [errors, setErrors] = useState({});
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();
  const { addToast } = useToast();

  useEffect(() => {
    // Redirect if already authenticated
    if (authService.isAuthenticated()) {
      navigate('/dashboard');
    }
  }, [navigate]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
    // Clear error for this field
    if (errors[name]) {
      setErrors(prev => ({ ...prev, [name]: '' }));
    }
  };

  const validateForm = () => {
    const newErrors = {};
    if (!formData.email.trim()) {
      newErrors.email = 'Email is required';
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email)) {
      newErrors.email = 'Please enter a valid email';
    }
    if (!formData.password) {
      newErrors.password = 'Password is required';
    }
    return newErrors;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    const newErrors = validateForm();
    
    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return;
    }

    setLoading(true);
    const result = await authService.login(formData.email, formData.password);
    
    if (result.ok) {
      addToast('Login successful!', 'success');
      navigate('/dashboard');
    } else {
      addToast(result.message || 'Login failed', 'error');
    }
    setLoading(false);
  };

  return (
    <main className="auth-page">
      <div className="container">
        <div className="auth-form-wrapper">
          <div className="auth-card">
            <h1>Login</h1>
            <p className="auth-subtitle">Welcome back! Login to your account</p>

            <form onSubmit={handleSubmit} noValidate>
              <div className="form-group">
                <label htmlFor="email">Email Address</label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                  className={errors.email ? 'field-error' : ''}
                  aria-describedby={errors.email ? 'email-error' : undefined}
                  disabled={loading}
                />
                {errors.email && (
                  <div id="email-error" className="error-message" role="alert">
                    ⚠️ {errors.email}
                  </div>
                )}
              </div>

              <div className="form-group">
                <label htmlFor="password">Password</label>
                <input
                  type="password"
                  id="password"
                  name="password"
                  value={formData.password}
                  onChange={handleChange}
                  className={errors.password ? 'field-error' : ''}
                  aria-describedby={errors.password ? 'password-error' : undefined}
                  disabled={loading}
                />
                {errors.password && (
                  <div id="password-error" className="error-message" role="alert">
                    ⚠️ {errors.password}
                  </div>
                )}
              </div>

              <button type="submit" className="btn btn-primary" disabled={loading}>
                {loading ? 'Logging in...' : 'Login'}
              </button>
            </form>

            <div className="auth-footer">
              <p>Don't have an account? <Link to="/auth/signup">Sign up</Link></p>
            </div>

            <div className="demo-credentials">
              <p><strong>Demo Credentials:</strong></p>
              <p>Email: demo@ticketapp.test</p>
              <p>Password: Password123!</p>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
};

// vue-app/src/pages/Login.vue
<template>
  <main class="auth-page">
    <div class="container">
      <div class="auth-form-wrapper">
        <div class="auth-card">
          <h1>Login</h1>
          <p class="auth-subtitle">Welcome back! Login to your account</p>

          <form @submit.prevent="handleSubmit" novalidate>
            <div class="form-group">
              <label for="email">Email Address</label>
              <input
                type="email"
                id="email"
                v-model="formData.email"
                :class="{ 'field-error': errors.email }"
                :aria-describedby="errors.email ? 'email-error' : undefined"
                :disabled="loading"
              />
              <div v-if="errors.email" id="email-error" class="error-message" role="alert">
                ⚠️ {{ errors.email }}
              </div>
            </div>

            <div class="form-group">
              <label for="password">Password</label>
              <input
                type="password"
                id="password"
                v-model="formData.password"
                :class="{ 'field-error': errors.password }"
                :aria-describedby="errors.password ? 'password-error' : undefined"
                :disabled="loading"
              />
              <div v-if="errors.password" id="password-error" class="error-message" role="alert">
                ⚠️ {{ errors.password }}
              </div>
            </div>

            <button type="submit" class="btn btn-primary" :disabled="loading">
              {{ loading ? 'Logging in...' : 'Login' }}
            </button>
          </form>

          <div class="auth-footer">
            <p>Don't have an account? <router-link to="/auth/signup">Sign up</router-link></p>
          </div>

          <div class="demo-credentials">
            <p><strong>Demo Credentials:</strong></p>
            <p>Email: demo@ticketapp.test</p>
            <p>Password: Password123!</p>
          </div>
        </div>
      </div>
    </div>
  </main>
</template>

<script setup>
import { ref, reactive, watch } from 'vue'
import { useRouter } from 'vue-router'
import { authService } from '../services/authService'
import { useToastStore } from '../stores/toastStore'

const router = useRouter()
const toastStore = useToastStore()
const formData = reactive({ email: '', password: '' })
const errors = reactive({})
const loading = ref(false)

watch(() => authService.isAuthenticated(), (isAuth) => {
  if (isAuth) {
    router.push('/dashboard')
  }
}, { immediate: true })

const validateForm = () => {
  const newErrors = {}
  if (!formData.email.trim()) {
    newErrors.email = 'Email is required'
  } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email)) {
    newErrors.email = 'Please enter a valid email'
  }
  if (!formData.password) {
    newErrors.password = 'Password is required'
  }
  return newErrors
}

const handleSubmit = async () => {
  const newErrors = validateForm()
  Object.assign(errors, newErrors)

  if (Object.keys(newErrors).length > 0) {
    return
  }

  loading.value = true
  const result = await authService.login(formData.email, formData.password)

  if (result.ok) {
    toastStore.addToast('Login successful!', 'success')
    router.push('/dashboard')
  } else {
    toastStore.addToast(result.message || 'Login failed', 'error')
  }
  loading.value = false
}
</script>

<style scoped src="../styles/auth.css"></style>
